[package]
name = "flexiargs"
version = "1.0.1"
edition = "2024"
description = "A flexible, rule-based command dispatcher and argument parser with strict level control."
license = "MIT"
authors = ["mxnt <m10ferrari1200@gmail.com>"]
documentation = "https://docs.rs/flexiargs/"
homepage = "https://github.com/LinuxProativo/flexiargs"
repository = "https://github.com/LinuxProativo/flexiargs"
readme = "README.md"
keywords = ["args", "arguments", "parse", "parser", "cli"]
categories = ["command-line-interface", "parsing"]
exclude = ["logo.png"]
